[package]
name = "voidedblades/react-lua-rodux-hooks"
description = "Roact hooks for Rodux using react-lua"
authors = ["SolarHorizon"]
version = "0.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
React = "jsdotlua/react@^17.1.0"
